// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dchain/whiteboard/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateWhiteboard struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XSize       uint64 `protobuf:"varint,4,opt,name=xSize,proto3" json:"xSize,omitempty"`
	YSize       uint64 `protobuf:"varint,5,opt,name=ySize,proto3" json:"ySize,omitempty"`
	IsLocked    bool   `protobuf:"varint,6,opt,name=isLocked,proto3" json:"isLocked,omitempty"`
}

func (m *MsgCreateWhiteboard) Reset()         { *m = MsgCreateWhiteboard{} }
func (m *MsgCreateWhiteboard) String() string { return proto.CompactTextString(m) }
func (*MsgCreateWhiteboard) ProtoMessage()    {}
func (*MsgCreateWhiteboard) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbe0b7f21d03227, []int{0}
}
func (m *MsgCreateWhiteboard) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateWhiteboard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateWhiteboard.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateWhiteboard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateWhiteboard.Merge(m, src)
}
func (m *MsgCreateWhiteboard) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateWhiteboard) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateWhiteboard.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateWhiteboard proto.InternalMessageInfo

func (m *MsgCreateWhiteboard) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateWhiteboard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateWhiteboard) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgCreateWhiteboard) GetXSize() uint64 {
	if m != nil {
		return m.XSize
	}
	return 0
}

func (m *MsgCreateWhiteboard) GetYSize() uint64 {
	if m != nil {
		return m.YSize
	}
	return 0
}

func (m *MsgCreateWhiteboard) GetIsLocked() bool {
	if m != nil {
		return m.IsLocked
	}
	return false
}

type MsgCreateWhiteboardResponse struct {
}

func (m *MsgCreateWhiteboardResponse) Reset()         { *m = MsgCreateWhiteboardResponse{} }
func (m *MsgCreateWhiteboardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateWhiteboardResponse) ProtoMessage()    {}
func (*MsgCreateWhiteboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbe0b7f21d03227, []int{1}
}
func (m *MsgCreateWhiteboardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateWhiteboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateWhiteboardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateWhiteboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateWhiteboardResponse.Merge(m, src)
}
func (m *MsgCreateWhiteboardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateWhiteboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateWhiteboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateWhiteboardResponse proto.InternalMessageInfo

type MsgLockWhiteboard struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	WhiteboardId uint64 `protobuf:"varint,2,opt,name=whiteboardId,proto3" json:"whiteboardId,omitempty"`
}

func (m *MsgLockWhiteboard) Reset()         { *m = MsgLockWhiteboard{} }
func (m *MsgLockWhiteboard) String() string { return proto.CompactTextString(m) }
func (*MsgLockWhiteboard) ProtoMessage()    {}
func (*MsgLockWhiteboard) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbe0b7f21d03227, []int{2}
}
func (m *MsgLockWhiteboard) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLockWhiteboard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLockWhiteboard.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLockWhiteboard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockWhiteboard.Merge(m, src)
}
func (m *MsgLockWhiteboard) XXX_Size() int {
	return m.Size()
}
func (m *MsgLockWhiteboard) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockWhiteboard.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockWhiteboard proto.InternalMessageInfo

func (m *MsgLockWhiteboard) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgLockWhiteboard) GetWhiteboardId() uint64 {
	if m != nil {
		return m.WhiteboardId
	}
	return 0
}

type MsgLockWhiteboardResponse struct {
}

func (m *MsgLockWhiteboardResponse) Reset()         { *m = MsgLockWhiteboardResponse{} }
func (m *MsgLockWhiteboardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLockWhiteboardResponse) ProtoMessage()    {}
func (*MsgLockWhiteboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbe0b7f21d03227, []int{3}
}
func (m *MsgLockWhiteboardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgLockWhiteboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgLockWhiteboardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgLockWhiteboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockWhiteboardResponse.Merge(m, src)
}
func (m *MsgLockWhiteboardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgLockWhiteboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockWhiteboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockWhiteboardResponse proto.InternalMessageInfo

type MsgUnlockWhiteboard struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	WhiteboardId uint64 `protobuf:"varint,2,opt,name=whiteboardId,proto3" json:"whiteboardId,omitempty"`
}

func (m *MsgUnlockWhiteboard) Reset()         { *m = MsgUnlockWhiteboard{} }
func (m *MsgUnlockWhiteboard) String() string { return proto.CompactTextString(m) }
func (*MsgUnlockWhiteboard) ProtoMessage()    {}
func (*MsgUnlockWhiteboard) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbe0b7f21d03227, []int{4}
}
func (m *MsgUnlockWhiteboard) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnlockWhiteboard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnlockWhiteboard.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnlockWhiteboard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnlockWhiteboard.Merge(m, src)
}
func (m *MsgUnlockWhiteboard) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnlockWhiteboard) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnlockWhiteboard.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnlockWhiteboard proto.InternalMessageInfo

func (m *MsgUnlockWhiteboard) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUnlockWhiteboard) GetWhiteboardId() uint64 {
	if m != nil {
		return m.WhiteboardId
	}
	return 0
}

type MsgUnlockWhiteboardResponse struct {
}

func (m *MsgUnlockWhiteboardResponse) Reset()         { *m = MsgUnlockWhiteboardResponse{} }
func (m *MsgUnlockWhiteboardResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnlockWhiteboardResponse) ProtoMessage()    {}
func (*MsgUnlockWhiteboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbe0b7f21d03227, []int{5}
}
func (m *MsgUnlockWhiteboardResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnlockWhiteboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnlockWhiteboardResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnlockWhiteboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnlockWhiteboardResponse.Merge(m, src)
}
func (m *MsgUnlockWhiteboardResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnlockWhiteboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnlockWhiteboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnlockWhiteboardResponse proto.InternalMessageInfo

type MsgSetWhiteboardPixelColor struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	WhiteboardId uint64 `protobuf:"varint,2,opt,name=whiteboardId,proto3" json:"whiteboardId,omitempty"`
	X            uint64 `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y            uint64 `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	R            uint64 `protobuf:"varint,5,opt,name=r,proto3" json:"r,omitempty"`
	G            uint64 `protobuf:"varint,6,opt,name=g,proto3" json:"g,omitempty"`
	B            uint64 `protobuf:"varint,7,opt,name=b,proto3" json:"b,omitempty"`
}

func (m *MsgSetWhiteboardPixelColor) Reset()         { *m = MsgSetWhiteboardPixelColor{} }
func (m *MsgSetWhiteboardPixelColor) String() string { return proto.CompactTextString(m) }
func (*MsgSetWhiteboardPixelColor) ProtoMessage()    {}
func (*MsgSetWhiteboardPixelColor) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbe0b7f21d03227, []int{6}
}
func (m *MsgSetWhiteboardPixelColor) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetWhiteboardPixelColor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetWhiteboardPixelColor.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetWhiteboardPixelColor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetWhiteboardPixelColor.Merge(m, src)
}
func (m *MsgSetWhiteboardPixelColor) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetWhiteboardPixelColor) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetWhiteboardPixelColor.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetWhiteboardPixelColor proto.InternalMessageInfo

func (m *MsgSetWhiteboardPixelColor) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetWhiteboardPixelColor) GetWhiteboardId() uint64 {
	if m != nil {
		return m.WhiteboardId
	}
	return 0
}

func (m *MsgSetWhiteboardPixelColor) GetX() uint64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *MsgSetWhiteboardPixelColor) GetY() uint64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *MsgSetWhiteboardPixelColor) GetR() uint64 {
	if m != nil {
		return m.R
	}
	return 0
}

func (m *MsgSetWhiteboardPixelColor) GetG() uint64 {
	if m != nil {
		return m.G
	}
	return 0
}

func (m *MsgSetWhiteboardPixelColor) GetB() uint64 {
	if m != nil {
		return m.B
	}
	return 0
}

type MsgSetWhiteboardPixelColorResponse struct {
}

func (m *MsgSetWhiteboardPixelColorResponse) Reset()         { *m = MsgSetWhiteboardPixelColorResponse{} }
func (m *MsgSetWhiteboardPixelColorResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetWhiteboardPixelColorResponse) ProtoMessage()    {}
func (*MsgSetWhiteboardPixelColorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fbe0b7f21d03227, []int{7}
}
func (m *MsgSetWhiteboardPixelColorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetWhiteboardPixelColorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetWhiteboardPixelColorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetWhiteboardPixelColorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetWhiteboardPixelColorResponse.Merge(m, src)
}
func (m *MsgSetWhiteboardPixelColorResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetWhiteboardPixelColorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetWhiteboardPixelColorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetWhiteboardPixelColorResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateWhiteboard)(nil), "dchain.whiteboard.MsgCreateWhiteboard")
	proto.RegisterType((*MsgCreateWhiteboardResponse)(nil), "dchain.whiteboard.MsgCreateWhiteboardResponse")
	proto.RegisterType((*MsgLockWhiteboard)(nil), "dchain.whiteboard.MsgLockWhiteboard")
	proto.RegisterType((*MsgLockWhiteboardResponse)(nil), "dchain.whiteboard.MsgLockWhiteboardResponse")
	proto.RegisterType((*MsgUnlockWhiteboard)(nil), "dchain.whiteboard.MsgUnlockWhiteboard")
	proto.RegisterType((*MsgUnlockWhiteboardResponse)(nil), "dchain.whiteboard.MsgUnlockWhiteboardResponse")
	proto.RegisterType((*MsgSetWhiteboardPixelColor)(nil), "dchain.whiteboard.MsgSetWhiteboardPixelColor")
	proto.RegisterType((*MsgSetWhiteboardPixelColorResponse)(nil), "dchain.whiteboard.MsgSetWhiteboardPixelColorResponse")
}

func init() { proto.RegisterFile("dchain/whiteboard/tx.proto", fileDescriptor_2fbe0b7f21d03227) }

var fileDescriptor_2fbe0b7f21d03227 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0xca, 0xd3, 0x40,
	0x14, 0xed, 0xd8, 0xf4, 0xc7, 0x6b, 0x91, 0x76, 0x14, 0x4c, 0x53, 0x0c, 0x21, 0x14, 0xe9, 0x42,
	0x53, 0xb0, 0xf8, 0x02, 0x76, 0x25, 0x18, 0xd0, 0x14, 0x11, 0xdc, 0xe5, 0x67, 0x48, 0x53, 0x6b,
	0x26, 0xcc, 0x04, 0x4c, 0xdc, 0xf8, 0x0a, 0x3e, 0x82, 0x2f, 0xe0, 0x5b, 0xb8, 0x70, 0xd9, 0xa5,
	0x4b, 0x69, 0x5f, 0x44, 0x32, 0x69, 0x52, 0xdb, 0x24, 0x50, 0xf9, 0xbe, 0x5d, 0xce, 0xb9, 0x87,
	0x7b, 0xe7, 0xe4, 0x1e, 0x2e, 0x28, 0x9e, 0xbb, 0xb6, 0x83, 0x70, 0xfe, 0x79, 0x1d, 0xc4, 0xc4,
	0xa1, 0x36, 0xf3, 0xe6, 0x71, 0x62, 0x44, 0x8c, 0xc6, 0x14, 0x8f, 0xf2, 0x9a, 0x71, 0xaa, 0xe9,
	0x3f, 0x10, 0x3c, 0x30, 0xb9, 0xbf, 0x64, 0xc4, 0x8e, 0xc9, 0xfb, 0x92, 0xc7, 0x32, 0xf4, 0xdc,
	0x8c, 0xa3, 0x4c, 0x46, 0x1a, 0x9a, 0xdd, 0xb5, 0x0a, 0x88, 0x31, 0x48, 0xa1, 0xfd, 0x89, 0xc8,
	0x77, 0x04, 0x2d, 0xbe, 0xb1, 0x06, 0xf7, 0x3c, 0xc2, 0x5d, 0x16, 0x44, 0x71, 0x40, 0x43, 0xb9,
	0x2d, 0x4a, 0xff, 0x52, 0xf8, 0x21, 0x74, 0x92, 0x55, 0xf0, 0x85, 0xc8, 0x92, 0x86, 0x66, 0x92,
	0x95, 0x83, 0x8c, 0x4d, 0x05, 0xdb, 0xc9, 0x59, 0x01, 0xb0, 0x02, 0xfd, 0x80, 0xbf, 0xa6, 0xee,
	0x47, 0xe2, 0xc9, 0x5d, 0x0d, 0xcd, 0xfa, 0x56, 0x89, 0xf5, 0xc7, 0x30, 0xa9, 0x79, 0xae, 0x45,
	0x78, 0x44, 0x43, 0x4e, 0xf4, 0xb7, 0x30, 0x32, 0xb9, 0x9f, 0x69, 0xaf, 0xf2, 0xa2, 0xc3, 0xe0,
	0xf4, 0x2f, 0x5e, 0x79, 0xc2, 0x93, 0x64, 0x9d, 0x71, 0xfa, 0x04, 0xc6, 0x95, 0x96, 0xe5, 0xbc,
	0x95, 0xf8, 0x7b, 0xef, 0xc2, 0xed, 0x6d, 0x4e, 0xcc, 0x3d, 0x5e, 0x36, 0x2d, 0x67, 0x7e, 0x47,
	0xa0, 0x98, 0xdc, 0x5f, 0x91, 0xf8, 0x54, 0x7c, 0x13, 0x24, 0x64, 0xbb, 0xa4, 0x5b, 0xca, 0x6e,
	0x36, 0x1b, 0x0f, 0x00, 0x25, 0x62, 0x7f, 0x92, 0x85, 0x92, 0x0c, 0xa5, 0xc7, 0x8d, 0xa1, 0x34,
	0x43, 0xec, 0xb8, 0x29, 0xc4, 0x32, 0xe4, 0x8b, 0xf5, 0x48, 0x16, 0xf2, 0x33, 0xe4, 0xc8, 0xbd,
	0x1c, 0x39, 0xfa, 0x14, 0xf4, 0xe6, 0x17, 0x16, 0x46, 0x9e, 0xff, 0x6c, 0x43, 0xdb, 0xe4, 0x3e,
	0xde, 0xc0, 0xb0, 0x92, 0xbf, 0x27, 0x46, 0x25, 0xab, 0x46, 0xcd, 0xe2, 0x15, 0xe3, 0x3a, 0x5d,
	0x31, 0x13, 0x7b, 0x70, 0xff, 0x22, 0x1d, 0xd3, 0xfa, 0x0e, 0xe7, 0x2a, 0xe5, 0xe9, 0x35, 0xaa,
	0x72, 0xca, 0x06, 0x86, 0x95, 0x4c, 0x34, 0x38, 0xba, 0xd4, 0x35, 0x39, 0x6a, 0x8a, 0x03, 0xfe,
	0x0a, 0x8f, 0x9a, 0xa2, 0xf0, 0xac, 0xbe, 0x55, 0x83, 0x5c, 0x79, 0xf1, 0x5f, 0xf2, 0xe2, 0x01,
	0x2f, 0x17, 0xbf, 0xf6, 0x2a, 0xda, 0xed, 0x55, 0xf4, 0x67, 0xaf, 0xa2, 0x6f, 0x07, 0xb5, 0xb5,
	0x3b, 0xa8, 0xad, 0xdf, 0x07, 0xb5, 0xf5, 0x61, 0x7c, 0xbc, 0x45, 0xc9, 0xd9, 0x35, 0x4a, 0x23,
	0xc2, 0x9d, 0xae, 0xb8, 0x48, 0x8b, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0x1b, 0x2e, 0xf3,
	0xaf, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateWhiteboard(ctx context.Context, in *MsgCreateWhiteboard, opts ...grpc.CallOption) (*MsgCreateWhiteboardResponse, error)
	LockWhiteboard(ctx context.Context, in *MsgLockWhiteboard, opts ...grpc.CallOption) (*MsgLockWhiteboardResponse, error)
	UnlockWhiteboard(ctx context.Context, in *MsgUnlockWhiteboard, opts ...grpc.CallOption) (*MsgUnlockWhiteboardResponse, error)
	SetWhiteboardPixelColor(ctx context.Context, in *MsgSetWhiteboardPixelColor, opts ...grpc.CallOption) (*MsgSetWhiteboardPixelColorResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateWhiteboard(ctx context.Context, in *MsgCreateWhiteboard, opts ...grpc.CallOption) (*MsgCreateWhiteboardResponse, error) {
	out := new(MsgCreateWhiteboardResponse)
	err := c.cc.Invoke(ctx, "/dchain.whiteboard.Msg/CreateWhiteboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LockWhiteboard(ctx context.Context, in *MsgLockWhiteboard, opts ...grpc.CallOption) (*MsgLockWhiteboardResponse, error) {
	out := new(MsgLockWhiteboardResponse)
	err := c.cc.Invoke(ctx, "/dchain.whiteboard.Msg/LockWhiteboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnlockWhiteboard(ctx context.Context, in *MsgUnlockWhiteboard, opts ...grpc.CallOption) (*MsgUnlockWhiteboardResponse, error) {
	out := new(MsgUnlockWhiteboardResponse)
	err := c.cc.Invoke(ctx, "/dchain.whiteboard.Msg/UnlockWhiteboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetWhiteboardPixelColor(ctx context.Context, in *MsgSetWhiteboardPixelColor, opts ...grpc.CallOption) (*MsgSetWhiteboardPixelColorResponse, error) {
	out := new(MsgSetWhiteboardPixelColorResponse)
	err := c.cc.Invoke(ctx, "/dchain.whiteboard.Msg/SetWhiteboardPixelColor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateWhiteboard(context.Context, *MsgCreateWhiteboard) (*MsgCreateWhiteboardResponse, error)
	LockWhiteboard(context.Context, *MsgLockWhiteboard) (*MsgLockWhiteboardResponse, error)
	UnlockWhiteboard(context.Context, *MsgUnlockWhiteboard) (*MsgUnlockWhiteboardResponse, error)
	SetWhiteboardPixelColor(context.Context, *MsgSetWhiteboardPixelColor) (*MsgSetWhiteboardPixelColorResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateWhiteboard(ctx context.Context, req *MsgCreateWhiteboard) (*MsgCreateWhiteboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWhiteboard not implemented")
}
func (*UnimplementedMsgServer) LockWhiteboard(ctx context.Context, req *MsgLockWhiteboard) (*MsgLockWhiteboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockWhiteboard not implemented")
}
func (*UnimplementedMsgServer) UnlockWhiteboard(ctx context.Context, req *MsgUnlockWhiteboard) (*MsgUnlockWhiteboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockWhiteboard not implemented")
}
func (*UnimplementedMsgServer) SetWhiteboardPixelColor(ctx context.Context, req *MsgSetWhiteboardPixelColor) (*MsgSetWhiteboardPixelColorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWhiteboardPixelColor not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateWhiteboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateWhiteboard)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateWhiteboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dchain.whiteboard.Msg/CreateWhiteboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateWhiteboard(ctx, req.(*MsgCreateWhiteboard))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LockWhiteboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLockWhiteboard)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LockWhiteboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dchain.whiteboard.Msg/LockWhiteboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LockWhiteboard(ctx, req.(*MsgLockWhiteboard))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnlockWhiteboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnlockWhiteboard)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnlockWhiteboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dchain.whiteboard.Msg/UnlockWhiteboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnlockWhiteboard(ctx, req.(*MsgUnlockWhiteboard))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetWhiteboardPixelColor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetWhiteboardPixelColor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetWhiteboardPixelColor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dchain.whiteboard.Msg/SetWhiteboardPixelColor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetWhiteboardPixelColor(ctx, req.(*MsgSetWhiteboardPixelColor))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dchain.whiteboard.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWhiteboard",
			Handler:    _Msg_CreateWhiteboard_Handler,
		},
		{
			MethodName: "LockWhiteboard",
			Handler:    _Msg_LockWhiteboard_Handler,
		},
		{
			MethodName: "UnlockWhiteboard",
			Handler:    _Msg_UnlockWhiteboard_Handler,
		},
		{
			MethodName: "SetWhiteboardPixelColor",
			Handler:    _Msg_SetWhiteboardPixelColor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dchain/whiteboard/tx.proto",
}

func (m *MsgCreateWhiteboard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateWhiteboard) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateWhiteboard) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsLocked {
		i--
		if m.IsLocked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.YSize != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.YSize))
		i--
		dAtA[i] = 0x28
	}
	if m.XSize != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.XSize))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateWhiteboardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateWhiteboardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateWhiteboardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgLockWhiteboard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLockWhiteboard) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLockWhiteboard) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WhiteboardId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WhiteboardId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgLockWhiteboardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgLockWhiteboardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgLockWhiteboardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUnlockWhiteboard) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnlockWhiteboard) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnlockWhiteboard) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WhiteboardId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WhiteboardId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnlockWhiteboardResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnlockWhiteboardResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnlockWhiteboardResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetWhiteboardPixelColor) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetWhiteboardPixelColor) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetWhiteboardPixelColor) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.B != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.B))
		i--
		dAtA[i] = 0x38
	}
	if m.G != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.G))
		i--
		dAtA[i] = 0x30
	}
	if m.R != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.R))
		i--
		dAtA[i] = 0x28
	}
	if m.Y != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Y))
		i--
		dAtA[i] = 0x20
	}
	if m.X != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.X))
		i--
		dAtA[i] = 0x18
	}
	if m.WhiteboardId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WhiteboardId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetWhiteboardPixelColorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetWhiteboardPixelColorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetWhiteboardPixelColorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateWhiteboard) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.XSize != 0 {
		n += 1 + sovTx(uint64(m.XSize))
	}
	if m.YSize != 0 {
		n += 1 + sovTx(uint64(m.YSize))
	}
	if m.IsLocked {
		n += 2
	}
	return n
}

func (m *MsgCreateWhiteboardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgLockWhiteboard) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WhiteboardId != 0 {
		n += 1 + sovTx(uint64(m.WhiteboardId))
	}
	return n
}

func (m *MsgLockWhiteboardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUnlockWhiteboard) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WhiteboardId != 0 {
		n += 1 + sovTx(uint64(m.WhiteboardId))
	}
	return n
}

func (m *MsgUnlockWhiteboardResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetWhiteboardPixelColor) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WhiteboardId != 0 {
		n += 1 + sovTx(uint64(m.WhiteboardId))
	}
	if m.X != 0 {
		n += 1 + sovTx(uint64(m.X))
	}
	if m.Y != 0 {
		n += 1 + sovTx(uint64(m.Y))
	}
	if m.R != 0 {
		n += 1 + sovTx(uint64(m.R))
	}
	if m.G != 0 {
		n += 1 + sovTx(uint64(m.G))
	}
	if m.B != 0 {
		n += 1 + sovTx(uint64(m.B))
	}
	return n
}

func (m *MsgSetWhiteboardPixelColorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateWhiteboard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateWhiteboard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateWhiteboard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field XSize", wireType)
			}
			m.XSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.XSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field YSize", wireType)
			}
			m.YSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.YSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsLocked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsLocked = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateWhiteboardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateWhiteboardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateWhiteboardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLockWhiteboard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLockWhiteboard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLockWhiteboard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhiteboardId", wireType)
			}
			m.WhiteboardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WhiteboardId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgLockWhiteboardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgLockWhiteboardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgLockWhiteboardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnlockWhiteboard) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnlockWhiteboard: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnlockWhiteboard: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhiteboardId", wireType)
			}
			m.WhiteboardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WhiteboardId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnlockWhiteboardResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnlockWhiteboardResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnlockWhiteboardResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetWhiteboardPixelColor) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetWhiteboardPixelColor: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetWhiteboardPixelColor: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhiteboardId", wireType)
			}
			m.WhiteboardId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WhiteboardId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X", wireType)
			}
			m.X = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.X |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y", wireType)
			}
			m.Y = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Y |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field R", wireType)
			}
			m.R = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.R |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field G", wireType)
			}
			m.G = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.G |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field B", wireType)
			}
			m.B = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.B |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetWhiteboardPixelColorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetWhiteboardPixelColorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetWhiteboardPixelColorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
